---
title: "Holocene veg reconstruction"
output: html_document
date: "2024-07-15"
---

```{r}
library(tidyverse)
```


```{r}
strain_data <- read.csv("/Users/nanqiangbeidiao/vegetation reconstruction/saved documents/training_data.csv") 
thresholds <- readRDS("/Users/nanqiangbeidiao/vegetation reconstruction/saved documents/non_analogue_thresholds.rds")
```



```{r}
pollen_samples <- janitor::clean_names(read.csv("/Users/nanqiangbeidiao/vegetation reconstruction/input dataset/only_new_age_model_entities/epd_gpd_samples.csv")) %>% mutate(age = as.double(age)) %>% dplyr::select(id_entity, id_sample, age) %>% filter(!is.na(age))
#107673obs

pollen_metadata <- janitor::clean_names(read.csv("/Users/nanqiangbeidiao/vegetation reconstruction/input dataset/only_new_age_model_entities/epd_gpd_metadata.csv")) %>% dplyr::select(id_entity, latitude, longitude)
#1884obs

pollen_amalgamated <- janitor::clean_names(read.csv("/Users/nanqiangbeidiao/vegetation reconstruction/input dataset/only_new_age_model_entities/epd_gpd_amalgamated.csv"))
#115709obs

pollen_samp_met <- inner_join(pollen_samples, pollen_metadata, by ="id_entity") 
#107673obs

pollen <-  inner_join(pollen_samp_met, pollen_amalgamated, by = "id_sample") %>%
  filter (latitude > min_lat & latitude < max_lat) %>% 
  filter (longitude > min_lon & longitude < max_lon) 
#106010 obs 
```



```{r}
pollen_fossil <- pollen %>%
  filter(age <= 12000) %>%
  pivot_longer(cols = -c(id_entity, id_sample, age, latitude, longitude)) |>
  filter(!is.na(value)) %>%
  group_by(id_sample) %>%
  mutate(total_sum = sum(value),
         percent = (value/total_sum)*100) %>%
  ungroup() %>%
  dplyr::select(-c(value,total_sum)) 
```


```{r}
all_fossil <- full_join(pollen_fossil,strain_data, by = "name") %>%
  filter(!is.na(percent)) %>% #delete na value in testing data.
  filter(!is.na(mean_taxa_STEP)) #delete na value in training data.

all_meta_fossil <- all_fossil %>% dplyr::select(id_entity, id_sample, age, latitude,longitude) %>% distinct() %>%
  mutate(age = as.double(age))
```


```{r}
EpsVal<- 0.5
dis_index_fossil <- all_fossil %>%
  mutate(Epsilon = EpsVal) %>%
  mutate(STEP_Sqrt=(percent-mean_taxa_STEP)^2/((sd_taxa_STEP+Epsilon)^2)) %>%
  mutate(WTMF_Sqrt=(percent-mean_taxa_WTMF)^2/((sd_taxa_WTMF+Epsilon)^2)) %>%
  mutate(XRTW_Sqrt=(percent-mean_taxa_XRTW)^2/((sd_taxa_XRTW+Epsilon)^2)) %>%
  mutate(TDBF_Sqrt=(percent-mean_taxa_TDBF)^2/((sd_taxa_TDBF+Epsilon)^2)) %>%
  mutate(CMXF_Sqrt=(percent-mean_taxa_CMXF)^2/((sd_taxa_CMXF+Epsilon)^2)) %>%
  mutate(CONF_Sqrt=(percent-mean_taxa_CONF)^2/((sd_taxa_CONF+Epsilon)^2)) %>%
  mutate(DESE_Sqrt=(percent-mean_taxa_DESE)^2/((sd_taxa_DESE+Epsilon)^2)) %>%
  mutate(TENW_Sqrt=(percent-mean_taxa_TENW)^2/((sd_taxa_TENW+Epsilon)^2)) %>%
  mutate(TUND_Sqrt=(percent-mean_taxa_TUND)^2/((sd_taxa_TUND+Epsilon)^2)) %>%
  mutate(CODF_Sqrt=(percent-mean_taxa_CODF)^2/((sd_taxa_CODF+Epsilon)^2)) %>%
  dplyr::select(id_sample,percent, id_entity, name, STEP_Sqrt, TDBF_Sqrt, CODF_Sqrt, TUND_Sqrt, CMXF_Sqrt, DESE_Sqrt, WTMF_Sqrt, XRTW_Sqrt, CONF_Sqrt, TENW_Sqrt)%>%
  group_by(id_sample) %>%
  summarise(across(c(TUND_Sqrt,CMXF_Sqrt,DESE_Sqrt,STEP_Sqrt, WTMF_Sqrt, XRTW_Sqrt, TDBF_Sqrt,CONF_Sqrt, TENW_Sqrt, CODF_Sqrt), sum )) %>% 
  mutate(across(c(TUND_Sqrt,CMXF_Sqrt, DESE_Sqrt,STEP_Sqrt, WTMF_Sqrt, XRTW_Sqrt, TDBF_Sqrt,CONF_Sqrt, TENW_Sqrt, CODF_Sqrt), sqrt)) %>% 
  ungroup()
```



```{r}
simi_index_fossil <- dis_index_fossil %>% 
  mutate(TUND=exp(-TUND_Sqrt/100)) %>% 
  mutate(DESE=exp(-DESE_Sqrt/100)) %>% 
  mutate(STEP=exp(-STEP_Sqrt/100)) %>% 
  mutate(XRTW=exp(-XRTW_Sqrt/100)) %>% 
  mutate(WTMF=exp(-WTMF_Sqrt/100)) %>% 
  mutate(TDBF=exp(-TDBF_Sqrt/100)) %>% 
  mutate(CMXF=exp(-CMXF_Sqrt/100)) %>% 
  mutate(CONF=exp(-CONF_Sqrt/100)) %>%
  mutate(TENW=exp(-TENW_Sqrt/100)) %>% 
  mutate(CODF=exp(-CODF_Sqrt/100)) %>% 
  dplyr::select(id_sample,TUND, DESE, STEP, WTMF, XRTW, TDBF, CMXF,CONF, TENW, CODF)
```



```{r}
predicted_biome <- simi_index_fossil %>% 
  pivot_longer(cols = -(id_sample), names_to = "predicted_biome") %>%
  group_by(id_sample) %>%
  arrange(id_sample,desc(value)) %>%
  slice_max(value, n=1) %>%
  ungroup() %>%
  inner_join(thresholds, by = c("predicted_biome"="biome")) %>%
  mutate(predicted_biome = case_when(value > threshold1 ~ predicted_biome, TRUE ~ "NONA"))
```


```{r}
predicted_biome <- predicted_biome %>% inner_join(all_meta_fossil) %>%
  filter(!is.na(age)) 
```

Calculate mean resolution of the records
```{r}
predicted_biome %>%
  group_by(id_entity) %>%
  mutate(
    anterior = lag(age),
    reso = age - anterior,
    resolucion = mean(reso, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  summarise(mean_resol = mean(resolucion, na.rm = TRUE))
```

Produce bins
```{r}
bin_width <- 200 # To ajust accordingly to the mean resolution of the records
overlap <- 0.5  # 50% overlap
age_min <- -bin_width/2
age_max <- 12000

biome_bin <- data.frame()
for (i in seq(age_min + bin_width/2, age_max, bin_width * (1 - overlap))) {
  
  bin_start <- i - bin_width / 2 
  bin_end <- i + bin_width / 2
  
  aux1 <- predicted_biome %>%
    filter(age >= bin_start & age < bin_end) %>% # Filter rows within the current bin
    mutate(bincentre = i)

  biome_bin <- bind_rows(biome_bin, aux1)
}
```


## Non-analogue analysis
```{r}
nona_perc <- biome_bin %>%
  group_by(bincentre) %>%
  dplyr::select(id_entity, predicted_biome, bincentre) %>%
  mutate(num_entities = n_distinct(id_entity),
         num_entities_NONA = n_distinct(id_entity[predicted_biome == "NONA"]),
         perc_entities_NONA = (num_entities_NONA/num_entities) * 100 ) %>%
  dplyr::select(bincentre, num_entities, num_entities_NONA, perc_entities_NONA) %>%
  distinct() 
```


```{r}
non_plot<- nona_perc %>%
  ggplot(aes(x=bincentre, y=perc_entities_NONA)) +
  geom_step() +
  geom_hline(yintercept = 5, linetype = "solid", color = "red", linewidth = 0.8) +
  scale_x_continuous(breaks = seq(0,12000, by=1000), labels = seq(0,12,by=1)) +
  labs(y = "proportion of entities (%)", x = "Age (ky)") +
  labs(subtitle = "Non analogue entities") + 
  theme_test()

non_plot

ggsave(plot = non_plot, filename = "non analogue percent.png", units = "cm", width = 20, height = 10)
```


## Forest analysis

```{r}
forest_perc <- biome_bin %>%
  filter(predicted_biome != "TRUE") %>%
  mutate(predicted_biome = case_when(predicted_biome %in% c("CMXF", "CODF", "CONF", "TDBF") ~ "FOREST", TRUE ~ "OTHERS")) %>%
  group_by(bincentre) %>%
  dplyr::select(id_entity, predicted_biome, bincentre) %>%
  mutate(num_entities = n_distinct(id_entity), #how many netities in total
         num_entities_FOREST = n_distinct(id_entity[predicted_biome == "FOREST"]), #how many forest entities in total
         perc_entities_FOREST = (num_entities_FOREST/num_entities) * 100 ) %>%
  dplyr::select(bincentre, num_entities, num_entities_FOREST, perc_entities_FOREST) %>%
  distinct()
```



```{r}
forest_plot <- forest_perc %>%
  ggplot(aes(x = bincentre, y = perc_entities_FOREST)) +
  geom_step() +
  scale_x_continuous(breaks = seq(0,12000, by=1000), labels = seq(0,12,by=1)) +
  labs(y = "Forest entities (%)", x = "Age (ky)", subtitle = "Biomes considered forest: CMIX, CODF, CONF, TDBF") +
  theme_test()

forest_plot

#ggsave(plot = forest_plot, filename = "forest percent.png", units = "cm", width = 20, height = 10)
```

## Mapping analysis

```{r}
colores<- c("XRTW"="#E6706E",
            "STEP"="#FAD272",
            "DESE"="#F7FFCA",
            "TDBF"="#FFC0CB",
            "TENW"="#8FB83E",
            "CODF"="#58D68D",
            "CMXF"="#A2D9CE",
            "CONF"="#239B56",
            "WTMF"="#CCCCFF",
            "CENF"="#B03E8D",
            "TUND"="#DFFF00",
            "TSNA"="#ed9121",
            "TDFW"="#858536",
            "TEBF"="#ffdddd",
            "TSBF"="#dce2b8")

land_polyg <- raster::shapefile("/Users/nanqiangbeidiao/Master_project/ne_10m_land/ne_10m_land.shp")

eurasia_polyg <- sp::spTransform(land_polyg, CRS("+proj=longlat +datum=WGS84")) %>%
    raster::crop(raster::extent(-10, 200, 15, 75)) %>%
    sf::st_as_sf()

tema_plots <- theme(plot.title=element_text(size=8, vjust=-1),
        plot.subtitle=element_text(size=8,vjust=-1),
        plot.margin = unit(c(0.3,0.3,0.3,0.3),"cm"),
            panel.grid = element_blank(),
            panel.background = element_rect(color="transparent", fill="transparent"),
            panel.border = element_rect(fill = "transparent",color="black",linewidth =0.4),
            axis.title.y = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size=8),
            axis.text.y = element_text(size=8),
            legend.text = element_text(size = 8),
            legend.key.height  = unit(3, "mm"),
            legend.key.width  = unit(1, "mm"),
            legend.key = element_rect(fill = "transparent",color="transparent"),
            legend.title = element_text(size = 6),
            legend.spacing = unit(1,"mm"),
            legend.margin = margin(unit = "cm", t=0,r=0.08,b=0.09,l=0.08),
            legend.background = element_rect(fill="transparent",color="gray30",linewidth=0.25),
            legend.position = c(0.846,0.146))

plot(eurasia_polyg)
```




```{r}
path_to_output <- "/Users/nanqiangbeidiao/vegetation reconstruction/final fossil reconstruction code/output_graph/"

for (i in seq(12000,0,-1000)) {

ventana <- 150
centro <- i

age_min <- centro - ventana
age_max <- centro + ventana

#Get the predicted biome within the window
period <- predicted_biome %>%
  filter(age>=age_min & age <=age_max) %>% 
  group_by(id_entity,predicted_biome) %>%
  add_tally(name = "samples_per_pred_biome") %>%
  mutate(sum_pred_score = sum(value)) %>%
  ungroup() %>%
  dplyr::select(id_entity,latitude,longitude,predicted_biome,samples_per_pred_biome,sum_pred_score) %>%
  distinct() %>%
  arrange(id_entity,desc(sum_pred_score)) %>%
  group_by(id_entity) %>%
  slice_max(samples_per_pred_biome, with_ties = F) %>%
  ungroup() 

#Plot time
map_youngest <- ggplot() +
  geom_sf(data=eurasia_polyg, fill="gray88", color="gray75",lwd=0.2, alpha=1) +
  geom_point(data = period, aes(x=longitude,y=latitude,fill=predicted_biome),shape=21,colour="gray15",size=1.6,stroke=0.3) +
  scale_fill_manual(values = colores) +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  guides(fill = FALSE) +
  annotate("text", x = 2, y = 70, label =paste(centro,"±",ventana,"yr",sep = ""),size=1.5) +
  labs(x=NULL, y=NULL,fill="Biome") +
  tema_plots 

print(map_youngest)

#ggsave(plot = map_youngest, filename = paste(path_to_output,centro," ± 150.pdf",sep = ""),units = "cm", width = 8,height =6)
ggsave(plot = map_youngest, filename = paste(path_to_output,centro," ± 150.png",sep = ""),units = "cm", width = 10,height =8)

}
```








